In [1]:
import torch
import jovian

<IPython.core.display.Javascript object>

In [2]:
# tensors torch is used to process tensors
# tensors store numbers and can be integers, vectors, matrices
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [4]:
t3 = torch.tensor([[2, 3], [4, 5], [7, 8]])
t3

tensor([[2, 3],
        [4, 5],
        [7, 8]])

In [5]:
t4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [6]:
t2.shape

torch.Size([4])

In [7]:
t3.shape

torch.Size([3, 2])

In [8]:
t4.shape

torch.Size([2, 2, 3])

In [9]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [10]:
# compute derivatives of values  wrt x, w, and b
y.backward()

In [11]:
print("dy/dx", x.grad)
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [12]:
# gradient with matrices and derivatives with numbers

In [13]:
import numpy as np
# numpy and pytorch are interoperable
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [14]:
# convert numpy array to tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [15]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [16]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Error: Failed to read pip environment using command: "pip --disable-pip-version-check freeze"


[jovian] Committed successfully! https://jovian.ai/psymbio/01-torch-and-numpy


'https://jovian.ai/psymbio/01-torch-and-numpy'

### What is PyTorch?

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing

### What is a Jupyter notebook?

this. (ooo... meta)

### What is Google Colab?

a similar env to jupyter, doesn't support binder, but it's nice too

### How do you install PyTorch?

pip3 install torch

### How do you import the torch module?

import torch

### What is a vector? Give an example.

A vector is an object that has both a magnitude and a direction. Like force is a vector.

### What is a matrix? Give an example.

In mathematics, a matrix (plural matrices) is a rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns. Like A = [2, 3, 4].

### What is a tensor?

https://en.wikipedia.org/wiki/Tensor

### How do you create a PyTorch tensor? Illustrate with examples.

t1 = torch.tensor(4.)

### What is the difference between a tensor and a vector or a matrix?

A tensor is often thought of as a generalized matrix. That is, it could be a 1-D matrix (a vector is actually such a tensor), a 3-D matrix (something like a cube of numbers), even a 0-D matrix (a single number), or a higher dimensional structure that is harder to visualize. The dimension of the tensor is called its rank. A tensor is a mathematical entity that lives in a structure and interacts with other mathematical entities. If one transforms the other entities in the structure in a regular way, then the tensor must obey a related transformation rule. This “dynamical” property of a tensor is the key that distinguishes it from a mere matrix. It’s a team player whose numerical values shift around along with those of its teammates when a transformation is introduced that affects all of them. Any rank-2 tensor can be represented as a matrix, but not every matrix is really a rank-2 tensor. The numerical values of a tensor’s matrix representation depend on what transformation rules have been applied to the entire system.

### Is every tensor a matrix?

yes.

### Is every matrix a tensor?

no.

### What does the dtype property of a tensor represent?

The datatype

### Is it possible to create a tensor with elements of different data types?

yes

### How do you inspect the number of dimensions of a tensor and the length along each dimension?

If you're calculating by hand start from the outer bracket going inwards, if not then t3.shape

### Is it possible to create a tensor with the values [[1, 2, 3], [4, 5]]? Why or why not?

No, the last row in the 2D matrix must have three values to be a valid tensor.

### How do you perform arithmetic operations on tensors? Illustrate with examples?

y = w * x + b, where w, x and b are tensors

### What happens if you specify requires_grad=True while creating a tensor? Illustrate with an example.

When you diffrentiate wrt to them they have a value, otherwise it gives the output as none.

### What is autograd in PyTorch? How is it useful?

autograd provides the automatic diffrentiation of the equation wrt to the variable that is declared as x = torch.ones(2, 2, requires_grad=True) such. 

<https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html>

### What happens when you invoke the backward method of a tensor?

If you want to compute the derivatives, you can call .backward() on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.

### How do you check the derivates of a result tensor w.r.t. the tensors used to compute its value?

print("dy/dw", w.grad)
print("dy/db", b.grad)

### Give some examples of functions available in the torch module for creating tensors.

t3 = torch.tensor([[2, 3], [4, 5], [7, 8]])
y = torch.from_numpy(x)

### Give some examples of functions available in the torch module for performing mathematical operations on tensors.

https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/
(This is a really good blog for GANs)

### Where can you find the list of tensor operations available in PyTorch?

https://pytorch.org/docs/stable/tensors.html

### What is Numpy?

Python library written in C for fast math computations, pytorch and numpy are interoperable.

### How do you create a Numpy array?

x = np.array([1, 2. 3])

### How do you create a PyTorch tensor using a Numpy array?

y = torch.from_numpy(x)

### How do you create a Numpy array using a PyTorch tensor?

z = y.numpy()

### Why is interoperability between PyTorch and Numpy important?

Because pytorch uses the GPU and nowadays it's all about that sweet-sweet GPU processing. Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.
Also before using the pytorch capabilitites most of the values need to be preprocessed by numpy.

### What is the purpose of a library like PyTorch if Numpy already provides data structures and utilities to with multi-dimensional numeric data?

Using the GPU which makes calclations faster, it would take days through numpy and just hours through pytorch

### What is Jovian?

host your jupyter files online, (I think I can use it for my website)

### How do you upload your notebooks to Jovian using jovian.commit?

will figure it out when I need to.