In [2]:
import torch

In [3]:
# tensors torch is used to process tensors
# tensors store numbers and can be integers, vectors, matrices
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3 = torch.tensor([[2, 3], [4, 5], [7, 8]])
t3

tensor([[2, 3],
        [4, 5],
        [7, 8]])

In [6]:
t4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [7]:
t2.shape

torch.Size([4])

In [9]:
t3.shape

torch.Size([3, 2])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [22]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [23]:
# compute derivatives of values  wrt x, w, and b
y.backward()

In [24]:
print("dy/dx", x.grad)
print("dy/dw", w.grad)
print("dy/db", b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [25]:
# gradient with matrices and derivatives with numbers

In [27]:
import numpy as np
# numpy and pytorch are interoperable
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [28]:
# convert numpy array to tensor
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [29]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)