In [1]:
import torch
import jovian
import numpy as np

<IPython.core.display.Javascript object>

In [2]:
t1 = torch.tensor([1, 2, 3])
a = torch.is_tensor(t1)
a

True

In [3]:
t1.numpy()
a = torch.is_tensor(t1)
a

True

In [4]:
a = torch.is_tensor(t1, 56)
a

TypeError: is_tensor() takes 1 positional argument but 2 were given

In [5]:
t2 = torch.randn(5, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
t2

tensor([ 2.6448,  0.3247, -0.0756, -0.3509,  1.0194])

In [6]:
d2 = torch.randn(67, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
d2

tensor([ 8.7414e-01, -3.2201e-01, -1.3161e-01, -1.5111e+00,  7.5260e-01,
        -8.3376e-01,  4.2400e-01,  1.1246e+00, -1.8620e-01, -3.2332e-04,
        -1.0843e+00,  7.8380e-01, -2.1887e+00,  2.7767e-01, -7.6738e-01,
         8.5883e-01, -6.1190e-01, -9.9692e-01,  4.7676e-02,  2.1169e-01,
         8.2142e-01, -1.5248e+00,  7.4900e-01,  2.0840e+00, -2.5571e+00,
         1.4186e+00,  2.0011e-01,  9.2506e-01, -2.0002e+00,  1.0417e+00,
        -7.9908e-01,  2.4942e-01, -2.1652e-01, -2.4483e-01, -3.3660e-02,
         5.7840e-01,  7.4862e-01, -1.2058e+00,  1.5864e+00, -1.9529e+00,
         1.4221e+00,  5.8073e-01, -2.8093e+00, -8.4365e-01,  1.4451e+00,
        -1.4656e+00,  3.8349e-02,  2.2905e-01,  2.1758e+00, -2.2774e-01,
        -9.8002e-01,  7.8993e-01, -1.4445e+00,  6.1779e-01,  3.5478e-01,
         1.1555e+00,  1.2500e-01,  1.7529e+00, -1.0082e+00, -1.3935e+00,
        -1.5510e-01, -2.0545e-01,  1.3474e+00, -1.0174e-01, -1.0170e+00,
        -1.5918e+00,  2.6200e-01])

In [7]:
c2 = torch.randn(67.8, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
c2

TypeError: randn() received an invalid combination of arguments - got (float, requires_grad=bool, device=NoneType, layout=torch.layout, dtype=NoneType, out=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [8]:
t3 = torch.full_like(t1, 5, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)
t3

tensor([5, 5, 5])

In [9]:
d3 = torch.full_like(t1, 45, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)
d3

tensor([45, 45, 45])

In [10]:
c3 = torch.full_like(7, 45, dtype=None, layout=torch.strided, device=None, requires_grad=False, memory_format=torch.preserve_format)
c3

TypeError: full_like(): argument 'input' (position 1) must be Tensor, not int

In [11]:
t4 = torch.tensor([1, 2], dtype=torch.float64)
t5 = torch.tensor([np.pi / 2, 5 * np.pi / 4], dtype=torch.float64)
t6 = torch.polar(t4, t5)
t6

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

In [12]:
t11 = torch.polar(t4, t5)
t11

tensor([ 6.1232e-17+1.0000j, -1.4142e+00-1.4142j], dtype=torch.complex128)

In [13]:
t9 = torch.polar(7, t5)
t9

TypeError: polar(): argument 'abs' (position 1) must be Tensor, not int

In [14]:
t7 = torch.sort(t2, dim=-1, descending=False)
t7

torch.return_types.sort(
values=tensor([-0.3509, -0.0756,  0.3247,  1.0194,  2.6448]),
indices=tensor([3, 2, 1, 4, 0]))

In [15]:
t12 = torch.sort(t11, dim=-1, descending=False)
t12

RuntimeError: method_name not implemented for 'ComplexDouble'

In [16]:
t13 = torch.sort(t4, dim=-1, descending=False)
t13

torch.return_types.sort(
values=tensor([1., 2.], dtype=torch.float64),
indices=tensor([0, 1]))

In [17]:
t1.shape

torch.Size([3])

In [18]:
t8 = torch.tensor(1)
b = torch.is_nonzero(t8)
b

True

In [19]:
t14 = torch.tensor([1])
f = torch.is_nonzero(t14)
f

True

In [20]:
t10 = torch.tensor([1, 2, 3, 4, 5])
c = torch.is_nonzero(t10)
c

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "psymbio/zerotogans-a1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Error: Failed to read pip environment using command: "pip --disable-pip-version-check freeze"


[jovian] Committed successfully! https://jovian.ai/psymbio/zerotogans-a1


'https://jovian.ai/psymbio/zerotogans-a1'

In [22]:
jovian.submit(assignment="zerotogans-a1")

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "psymbio/zerotogans-a1" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..


[jovian] Error: Failed to read Anaconda environment using command: "conda env export -n base --no-builds"
[jovian] Error: Failed to read pip environment using command: "pip --disable-pip-version-check freeze"


[jovian] Committed successfully! https://jovian.ai/psymbio/zerotogans-a1
[jovian] Submitting assignment..
[jovian] Verify your submission at https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor
